apiVersion: v1
kind: Service
metadata:
  name: {{ include "chart.fullname" . }}-ssh
  labels:
    {{- include "chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 2022
      protocol: TCP
      name: ssh
  selector:
    {{- include "chart.selectorLabels" . | nindent 4 }}
